---
# OLM: BEGIN ROLE
# Aspects for creation of monitoring resources
kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: netbox-monitor
  namespace: netbox-community
rules:
- apiGroups:
  - monitoring.coreos.com
  resources:
  - '*'
  verbs:
  - '*'
# OLM: END ROLE
---
# OLM: BEGIN ROLE BINDING
# Allow creation of monitoring resources
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: netbox-monitor
  namespace: netbox-community
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: netbox-monitor
subjects:
- kind: ServiceAccount
  name: netbox
  namespace: netbox-community
# OLM: END ROLE BINDING
---
# OLM: BEGIN ROLE
# Aspects for metrics collection
kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: netbox-metrics
  namespace: netbox-community
rules:
 - apiGroups:
   - ""
   resources:
    - services
    - endpoints
    - pods
   verbs:
    - get
    - list
    - watch
# OLM: END ROLE
---
# OLM: BEGIN ROLE BINDING
# Allow collection of metrics
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: netbox-metrics
  namespace: netbox-community
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: netbox-metrics
subjects:
- kind: ServiceAccount
  # change to the serviceaccount and namespace to use for monitoring
  name: prometheus-k8s
  namespace: monitoring
# OLM: END ROLE BINDING
---